# App custom command permissions
"$schema" = "./schemas/schema.json"

[[permission]]
identifier = "allow-get-settings"
description = "Enables the get_settings command."
commands.allow = ["get_settings"]

[[permission]]
identifier = "deny-get-settings"
description = "Denies the get_settings command."
commands.deny = ["get_settings"]

[[permission]]
identifier = "allow-set-settings"
description = "Enables the set_settings command."
commands.allow = ["set_settings"]

[[permission]]
identifier = "deny-set-settings"
description = "Denies the set_settings command."
commands.deny = ["set_settings"]

[[permission]]
identifier = "allow-get-monitors"
description = "Enables the get_monitors command."
commands.allow = ["get_monitors"]

[[permission]]
identifier = "deny-get-monitors"
description = "Denies the get_monitors command."
commands.deny = ["get_monitors"]

[[permission]]
identifier = "allow-get-notch-inset"
description = "Enables the get_notch_inset command."
commands.allow = ["get_notch_inset"]

[[permission]]
identifier = "deny-get-notch-inset"
description = "Denies the get_notch_inset command."
commands.deny = ["get_notch_inset"]
